### ISSUE TITLE
Wrong path to the project cloning HTTPs, in the installation section.

### ISSUE THREAD

**Issue by CarlosNacher** [OscarPellicer/Deep-Learning-in-Prostate-PhD#1]
Hi Oscar,

In the installation section, you give the command `git clone https://github.com/OscarPellicer/Deep-Learning-in-Prostate-PhD.git` to clone the project. This gives an error, the **"in"** is left out. The correct path is `https://github.com/OscarPellicer/Deep-Learning-Prostate-PhD.git`.

Best regards!

**Comment by OscarPellicer** [comment]
It was the name of the repo itself that was wrong 😅
It should now be fixed
